name: cart
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  intl: ^0.18.1
  intl_utils: ^2.8.7
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.0+4
  flutter_bloc: ^8.1.4
  path_provider: ^2.1.2
  path: ^1.8.3
  logger: ^2.1.0
  equatable: ^2.0.5
  dio_cache_interceptor: ^3.5.0
  dio_smart_retry: ^6.0.0
  sqflite_common_ffi_web: ^0.4.2+1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
  # 根据arb文件生成dart文件
  generate: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/generated/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
  
  colors:
    inputs:
      - assets/color/colors.xml

flutter_intl:
  enabled: true
