name: cart
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  intl: ^0.18.1
  intl_utils: ^2.8.7
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.0+4
  flutter_bloc: ^8.1.4
  path_provider: ^2.1.2
  path: ^1.8.3
  logger: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # 根据arb文件生成dart文件
  generate: true
